In [11]:
import polars as pl

df = pl.read_csv("https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing.csv")

In [12]:
df = df.filter(pl.col("bedrooms") <= 20)

In [14]:
df.select(pl.max("bedrooms"))
df.write_csv("data/clean.csv")

In [8]:
df.write_csv("data/raw.csv")

In [ ]:
df.describe()
["bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors", "sqft_above", "sqft_basement"]

shape: (9, 22)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ id        ┆ date      ┆ bedrooms ┆ … ┆ long      ┆ sqft_livi ┆ sqft_lot1 ┆ price     │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ng15      ┆ 5         ┆ ---       │
│ str       ┆ f64       ┆ str       ┆ f64      ┆   ┆ f64       ┆ ---       ┆ ---       ┆ f64       │
│           ┆           ┆           ┆          ┆   ┆           ┆ f64       ┆ f64       ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 20000.0   ┆ 20000     ┆ 20000.0  ┆ … ┆ 20000.0   ┆ 20000.0   ┆ 20000.0   ┆ 20000.0   │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ 4.5803e9  ┆ null      ┆ 3.3702   ┆ … ┆ -122.2138 ┆ 1986.3875 ┆ 12748.960 ┆ 539436.71 │
│           ┆           ┆           ┆          ┆   ┆ 97        ┆           ┆ 4         ┆ 295       │
│ std       ┆ 2.8753e9  ┆ null      ┆ 0.931931 ┆ … ┆ 0.140649  ┆ 685.21151 ┆ 27076.489 ┆ 366433.43 │
│           ┆           ┆           ┆          ┆   ┆           ┆ 5         ┆ 04        ┆ 6119      │
│ min       ┆ 1.000102e ┆ 20140502T ┆ 0.0      ┆ … ┆ -122.519  ┆ 399.0     ┆ 651.0     ┆ 75000.0   │
│           ┆ 6         ┆ 000000    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ 2.1230e9  ┆ null      ┆ 3.0      ┆ … ┆ -122.328  ┆ 1490.0    ┆ 5100.0    ┆ 322000.0  │
│ 50%       ┆ 3.9050e9  ┆ null      ┆ 3.0      ┆ … ┆ -122.23   ┆ 1840.0    ┆ 7622.0    ┆ 450000.0  │
│ 75%       ┆ 7.3091e9  ┆ null      ┆ 4.0      ┆ … ┆ -122.124  ┆ 2360.0    ┆ 10088.0   ┆ 641500.0  │
│ max       ┆ 9.9000e9  ┆ 20150527T ┆ 33.0     ┆ … ┆ -121.315  ┆ 6210.0    ┆ 871200.0  ┆ 7.7e6     │
│           ┆           ┆ 000000    ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
df.head()

shape: (5, 21)
┌────────────┬────────────┬──────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ id         ┆ date       ┆ bedrooms ┆ bathrooms ┆ … ┆ long     ┆ sqft_livi ┆ sqft_lot1 ┆ price    │
│ ---        ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ng15      ┆ 5         ┆ ---      │
│ i64        ┆ str        ┆ i64      ┆ f64       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ f64      │
│            ┆            ┆          ┆           ┆   ┆          ┆ i64       ┆ i64       ┆          │
╞════════════╪════════════╪══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 1565930130 ┆ 20141104T0 ┆ 4        ┆ 3.25      ┆ … ┆ -122.048 ┆ 3280      ┆ 4033      ┆ 429900.0 │
│            ┆ 00000      ┆          ┆           ┆   ┆          ┆           ┆           ┆          │
│ 3279000420 ┆ 20150115T0 ┆ 3        ┆ 1.75      ┆ … ┆ -122.382 ┆ 1310      ┆ 7865      ┆ 233000.0 │
│            ┆ 00000      ┆          ┆           ┆   ┆          ┆           ┆           ┆          │
│ 194000575  ┆ 20141014T0 ┆ 4        ┆ 1.0       ┆ … ┆ -122.389 ┆ 1900      ┆ 5800      ┆ 455000.0 │
│            ┆ 00000      ┆          ┆           ┆   ┆          ┆           ┆           ┆          │
│ 2115510160 ┆ 20141208T0 ┆ 3        ┆ 1.75      ┆ … ┆ -122.39  ┆ 1790      ┆ 7488      ┆ 258950.0 │
│            ┆ 00000      ┆          ┆           ┆   ┆          ┆           ┆           ┆          │
│ 7522500005 ┆ 20140815T0 ┆ 2        ┆ 1.5       ┆ … ┆ -122.395 ┆ 1690      ┆ 5962      ┆ 555000.0 │
│            ┆ 00000      ┆          ┆           ┆   ┆          ┆           ┆           ┆          │
└────────────┴────────────┴──────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [20]:
pl.Config.set_tbl_rows(70)
pl.Config.set_fmt_float("full")
(
    df
    .group_by("zipcode")
    .agg(
        mean_price = pl.col("price").mean(),
        median_price = pl.col("price").median(),
        max_price = pl.col("price").max(),
        built_mode = pl.col("yr_built").mode(),
        mean_sqft = pl.col("sqft_living15").mean(),
        median_bedrooms = pl.col("bedrooms").median(),
        median_bathrooms = pl.col("bathrooms").median(),
        median_floors = pl.col("floors").median(),
        median_condition = pl.col("condition").median(),
        median_grade = pl.col("grade").median(),
        avg_grade = pl.col("grade").mean(),
        num_of_houses = pl.len()
        )
    .sort("mean_price", descending=True)
)

shape: (70, 13)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ zipcode ┆ mean_price ┆ median_pr ┆ max_price ┆ … ┆ median_co ┆ median_gr ┆ avg_grade ┆ num_of_ho │
│ ---     ┆ ---        ┆ ice       ┆ ---       ┆   ┆ ndition   ┆ ade       ┆ ---       ┆ uses      │
│ i64     ┆ f64        ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ---       │
│         ┆            ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ u32       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 98039   ┆ 2166618.04 ┆ 1892500   ┆ 6885000   ┆ … ┆ 3         ┆ 9         ┆ 9.5434782 ┆ 46        │
│         ┆ 34782607   ┆           ┆           ┆   ┆           ┆           ┆ 60869565  ┆           │
│ 98004   ┆ 1361288.31 ┆ 1162500   ┆ 7062500   ┆ … ┆ 3         ┆ 8         ┆ 8.6805555 ┆ 288       │
│         ┆ 94444445   ┆           ┆           ┆   ┆           ┆           ┆ 55555555  ┆           │
│ 98040   ┆ 1206933.13 ┆ 997000    ┆ 5300000   ┆ … ┆ 4         ┆ 9         ┆ 8.9724409 ┆ 254       │
│         ┆ 38582677   ┆           ┆           ┆   ┆           ┆           ┆ 44881889  ┆           │
│ 98112   ┆ 1095133.22 ┆ 906000    ┆ 3400000   ┆ … ┆ 3         ┆ 8         ┆ 8.4538152 ┆ 249       │
│         ┆ 48995984   ┆           ┆           ┆   ┆           ┆           ┆ 61044177  ┆           │
│ 98102   ┆ 905087.555 ┆ 720000    ┆ 7700000   ┆ … ┆ 3         ┆ 8         ┆ 8.3131313 ┆ 99        │
│         ┆ 5555555    ┆           ┆           ┆   ┆           ┆           ┆ 13131313  ┆           │
│ 98109   ┆ 878483.080 ┆ 736000    ┆ 3200000   ┆ … ┆ 3         ┆ 8         ┆ 8.0404040 ┆ 99        │
│         ┆ 8080808    ┆           ┆           ┆   ┆           ┆           ┆ 4040404   ┆           │
│ 98006   ┆ 871625.803 ┆ 770000    ┆ 4208000   ┆ … ┆ 4         ┆ 9         ┆ 8.8268398 ┆ 462       │
│         ┆ 030303     ┆           ┆           ┆   ┆           ┆           ┆ 26839826  ┆           │
│ 98105   ┆ 847226.045 ┆ 671912    ┆ 2950000   ┆ … ┆ 3         ┆ 8         ┆ 7.8165137 ┆ 218       │
│         ┆ 8715596    ┆           ┆           ┆   ┆           ┆           ┆ 6146789   ┆           │
│ 98119   ┆ 847201.547 ┆ 737500    ┆ 3065000   ┆ … ┆ 3         ┆ 8         ┆ 8.0476190 ┆ 168       │
│         ┆ 6190476    ┆           ┆           ┆   ┆           ┆           ┆ 47619047  ┆           │
│ 98005   ┆ 802868.867 ┆ 760000    ┆ 1960000   ┆ … ┆ 4         ┆ 8         ┆ 8.4635761 ┆ 151       │
│         ┆ 5496689    ┆           ┆           ┆   ┆           ┆           ┆ 58940397  ┆           │
│ 98033   ┆ 801808.5   ┆ 675000    ┆ 5110800   ┆ … ┆ 3         ┆ 8         ┆ 8.0693069 ┆ 404       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ 30693068  ┆           │
│ 98075   ┆ 793867.712 ┆ 739999    ┆ 3200000   ┆ … ┆ 3         ┆ 9         ┆ 9.0296735 ┆ 337       │
│         ┆ 1661721    ┆           ┆           ┆   ┆           ┆           ┆ 90504451  ┆           │
│ 98199   ┆ 782575.754 ┆ 689800    ┆ 2795000   ┆ … ┆ 3         ┆ 8         ┆ 8.0273037 ┆ 293       │
│         ┆ 2662116    ┆           ┆           ┆   ┆           ┆           ┆ 54266212  ┆           │
│ 98177   ┆ 685590.238 ┆ 560000    ┆ 3800000   ┆ … ┆ 3         ┆ 8         ┆ 7.9783549 ┆ 231       │
│         ┆ 0952381    ┆           ┆           ┆   ┆           ┆           ┆ 78354979  ┆           │
│ 98074   ┆ 681641.603 ┆ 639500    ┆ 3075000   ┆ … ┆ 3         ┆ 9         ┆ 8.6748768 ┆ 406       │
│         ┆ 4482758    ┆           ┆           ┆   ┆           ┆           ┆ 4729064   ┆           │
│ 98077   ┆ 681230.005 ┆ 650000    ┆ 1920000   ┆ … ┆ 3         ┆ 9         ┆ 8.7891891 ┆ 185       │
│         ┆ 4054054    ┆           ┆           ┆   ┆           ┆           ┆ 8918919   ┆           │
│ 98053   ┆ 675331.4   ┆ 629495    ┆ 2280000   ┆ … ┆ 3         ┆ 8         ┆ 8.2657894 ┆ 380       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ 7368421   ┆           │
│ 98008   ┆ 651104.643 ┆ 546800    ┆ 3567000   ┆ … ┆ 4         ┆ 7         ┆ 7.6819923 ┆ 261       │
│         ┆ 678161     ┆           ┆           ┆   ┆           ┆           ┆ 37164751  ┆           │
│ 98052   ┆ 647767.548 ┆ 620000    ┆ 2200000   ┆ … ┆ 3         ┆ 8         ┆ 8.2033582 ┆ 536       │
│         ┆ 5074627    ┆           ┆           ┆   ┆           ┆           ┆ 08955224  ┆           │
│ 98122   ┆ 636686.124 ┆ 572000    ┆ 2050000   ┆ … ┆ 3         ┆ 8         ┆ 7.7480620 ┆ 258       │
│         ┆ 0310078    ┆           ┆           ┆   ┆           ┆           ┆ 15503876  ┆           │
│ 98116   ┆ 623072.324 ┆ 566500    ┆ 2050000   ┆ … ┆ 3         ┆ 7         ┆ 7.5746753 ┆ 308       │
│         ┆ 6753247    ┆           ┆           ┆   ┆           ┆           ┆ 24675325  ┆           │
│ 98027   ┆ 620358.611 ┆ 573475    ┆ 2700000   ┆ … ┆ 3         ┆ 8         ┆ 8.2072538 ┆ 386       │
│         ┆ 3989637    ┆           ┆           ┆   ┆           ┆           ┆ 86010363  ┆           │
│ 98115   ┆ 618262.111 ┆ 562750    ┆ 2300000   ┆ … ┆ 3         ┆ 7         ┆ 7.3584905 ┆ 530       │
│         ┆ 3207547    ┆           ┆           ┆   ┆           ┆           ┆ 660377355 ┆           │
│ 98029   ┆ 615265.885 ┆ 575000    ┆ 2200000   ┆ … ┆ 3         ┆ 8         ┆ 8.3939393 ┆ 297       │
│         ┆ 5218855    ┆           ┆           ┆   ┆           ┆           ┆ 93939394  ┆           │
│ 98007   ┆ 611196.291 ┆ 550000    ┆ 1315000   ┆ … ┆ 4         ┆ 8         ┆ 7.9291338 ┆ 127       │
│         ┆ 3385826    ┆           ┆           ┆   ┆           ┆           ┆ 58267717  ┆           │
│ 98103   ┆ 582589.103 ┆ 552000    ┆ 1695000   ┆ … ┆ 3         ┆ 7         ┆ 7.4085257 ┆ 563       │
│         ┆ 0195382    ┆           ┆           ┆   ┆           ┆           ┆ 54884547  ┆           │
│ 98117   ┆ 578983.053 ┆ 545000    ┆ 1370000   ┆ … ┆ 3         ┆ 7         ┆ 7.2859884 ┆ 521       │
│         ┆ 7428024    ┆           ┆           ┆   ┆           ┆           ┆ 836852205 ┆           │
│ 98107   ┆ 573787.179 ┆ 529950    ┆ 2945000   ┆ … ┆ 3         ┆ 7         ┆ 7.4122448 ┆ 245       │
│         ┆ 5918368    ┆           ┆           ┆   ┆           ┆           ┆ 97959184  ┆           │
│ 98144   ┆ 573734.588 ┆ 450000    ┆ 2725000   ┆ … ┆ 3         ┆ 7         ┆ 7.4308176 ┆ 318       │
│         ┆ 0503145    ┆           ┆           ┆   ┆           ┆           ┆ 10062893  ┆           │
│ 98024   ┆ 568559.871 ┆ 458500    ┆ 1862000   ┆ … ┆ 3         ┆ 7         ┆ 7.5       ┆ 78        │
│         ┆ 7948718    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 98072   ┆ 567887.792 ┆ 515000    ┆ 1565000   ┆ … ┆ 3         ┆ 8         ┆ 8.0836653 ┆ 251       │
│         ┆ 8286853    ┆           ┆           ┆   ┆           ┆           ┆ 3864542   ┆           │
│ 98136   ┆ 550508.861 ┆ 485000    ┆ 2230000   ┆ … ┆ 3         ┆ 7         ┆ 7.3795918 ┆ 245       │
│         ┆ 2244898    ┆           ┆           ┆   ┆           ┆           ┆ 367346935 ┆           │
│ 98065   ┆ 532883.243 ┆ 505000    ┆ 1998000   ┆ … ┆ 3         ┆ 8         ┆ 7.8989547 ┆ 287       │
│         ┆ 902439     ┆           ┆           ┆   ┆           ┆           ┆ 03832753  ┆           │
│ 98034   ┆ 517811.042 ┆ 446000    ┆ 3120000   ┆ … ┆ 3         ┆ 7         ┆ 7.5020080 ┆ 498       │
│         ┆ 1686747    ┆           ┆           ┆   ┆           ┆           ┆ 32128514  ┆           │
│ 98059   ┆ 492028.506 ┆ 430000    ┆ 1780000   ┆ … ┆ 3         ┆ 8         ┆ 7.8721973 ┆ 446       │
│         ┆ 7264574    ┆           ┆           ┆   ┆           ┆           ┆ 0941704   ┆           │
│ 98011   ┆ 490100.759 ┆ 470000    ┆ 1075000   ┆ … ┆ 3         ┆ 8         ┆ 7.7877094 ┆ 179       │
│         ┆ 7765363    ┆           ┆           ┆   ┆           ┆           ┆ 97206704  ┆           │
│ 98070   ┆ 484194.491 ┆ 457750    ┆ 1379900   ┆ … ┆ 4         ┆ 7         ┆ 7.2327586 ┆ 116       │
│         ┆ 3793103    ┆           ┆           ┆   ┆           ┆           ┆ 20689655  ┆           │
│ 98125   ┆ 470063.857 ┆ 425000    ┆ 2050000   ┆ … ┆ 3         ┆ 7         ┆ 7.1815789 ┆ 380       │
│         ┆ 89473687   ┆           ┆           ┆   ┆           ┆           ┆ 47368421  ┆           │
│ 98028   ┆ 463319.074 ┆ 445500    ┆ 1600000   ┆ … ┆ 3         ┆ 7         ┆ 7.6185185 ┆ 270       │
│         ┆ 0740741    ┆           ┆           ┆   ┆           ┆           ┆ 18518519  ┆           │
│ 98166   ┆ 456364.025 ┆ 390000    ┆ 2125000   ┆ … ┆ 3         ┆ 7         ┆ 7.3949579 ┆ 238       │
│         ┆ 21008404   ┆           ┆           ┆   ┆           ┆           ┆ 83193278  ┆           │
│ 98014   ┆ 451176.070 ┆ 416500    ┆ 1680000   ┆ … ┆ 3         ┆ 7         ┆ 7.3596491 ┆ 114       │
│         ┆ 1754386    ┆           ┆           ┆   ┆           ┆           ┆ 22807017  ┆           │
│ 98010   ┆ 432723.877 ┆ 372000    ┆ 935000    ┆ … ┆ 3         ┆ 7         ┆ 7.4333333 ┆ 90        │
│         ┆ 7777778    ┆           ┆           ┆   ┆           ┆           ┆ 33333334  ┆           │
│ 98045   ┆ 431833.864 ┆ 392000    ┆ 1950000   ┆ … ┆ 3         ┆ 7         ┆ 7.5929648 ┆ 199       │
│         ┆ 32160804   ┆           ┆           ┆   ┆           ┆           ┆ 24120603  ┆           │
│ 98155   ┆ 427333.829 ┆ 382250    ┆ 4500000   ┆ … ┆ 3         ┆ 7         ┆ 7.1881188 ┆ 404       │
│         ┆ 2079208    ┆           ┆           ┆   ┆           ┆           ┆ 11881188  ┆           │
│ 98019   ┆ 426492.245 ┆ 403000    ┆ 1015000   ┆ … ┆ 3         ┆ 7         ┆ 7.5083798 ┆ 179       │
│         ┆ 8100559    ┆           ┆           ┆   ┆           ┆           ┆ 882681565 ┆           │
│ 98056   ┆ 423963.211 ┆ 380000    ┆ 3000000   ┆ … ┆ 4         ┆ 7         ┆ 7.3743315 ┆ 374       │
│         ┆ 2299465    ┆           ┆           ┆   ┆           ┆           ┆ 50802139  ┆           │
│ 98126   ┆ 419325.189 ┆ 393000    ┆ 1085000   ┆ … ┆ 3         ┆ 7         ┆ 6.9968944 ┆ 322       │
│         ┆ 44099377   ┆           ┆           ┆   ┆           ┆           ┆ 09937888  ┆           │
│ 98118   ┆ 415319.259 ┆ 365000    ┆ 2903000   ┆ … ┆ 3         ┆ 7         ┆ 6.9574468 ┆ 470       │
│         ┆ 5744681    ┆           ┆           ┆   ┆           ┆           ┆ 08510638  ┆           │
│ 98133   ┆ 386346.803 ┆ 374575    ┆ 808100    ┆ … ┆ 3         ┆ 7         ┆ 7.1409691 ┆ 454       │
│         ┆ 9647577    ┆           ┆           ┆   ┆           ┆           ┆ 62995595  ┆           │
│ 98038   ┆ 367155.247 ┆ 341000    ┆ 1350000   ┆ … ┆ 3         ┆ 7         ┆ 7.5963636 ┆ 550       │
│         ┆ 27272725   ┆           ┆           ┆   ┆           ┆           ┆ 36363637  ┆           │
│ 98146   ┆ 356885.492 ┆ 302550    ┆ 1410000   ┆ … ┆ 3         ┆ 7         ┆ 6.8185185 ┆ 270       │
│         ┆ 5925926    ┆           ┆           ┆   ┆           ┆           ┆ 18518519  ┆           │
│ 98108   ┆ 356162.782 ┆ 346500    ┆ 635000    ┆ … ┆ 3         ┆ 7         ┆ 7.0114285 ┆ 175       │
│         ┆ 85714285   ┆           ┆           ┆   ┆           ┆           ┆ 71428572  ┆           │
│ 98058   ┆ 350382.103 ┆ 335000    ┆ 1135250   ┆ … ┆ 3         ┆ 7         ┆ 7.5531400 ┆ 414       │
│         ┆ 8647343    ┆           ┆           ┆   ┆           ┆           ┆ 96618358  ┆           │
│ 98092   ┆ 332313.824 ┆ 308000    ┆ 905000    ┆ … ┆ 3         ┆ 8         ┆ 7.8184615 ┆ 325       │
│         ┆ 6153846    ┆           ┆           ┆   ┆           ┆           ┆ 38461539  ┆           │
│ 98106   ┆ 321971.133 ┆ 315000    ┆ 795000    ┆ … ┆ 3         ┆ 7         ┆ 6.8758169 ┆ 306       │
│         ┆ 9869281    ┆           ┆           ┆   ┆           ┆           ┆ 93464053  ┆           │
│ 98022   ┆ 312526.234 ┆ 277500    ┆ 858000    ┆ … ┆ 4         ┆ 7         ┆ 7.1455399 ┆ 213       │
│         ┆ 74178405   ┆           ┆           ┆   ┆           ┆           ┆ 06103286  ┆           │
│ 98042   ┆ 312046.944 ┆ 294500    ┆ 859000    ┆ … ┆ 3         ┆ 7         ┆ 7.4367588 ┆ 506       │
│         ┆ 6640316    ┆           ┆           ┆   ┆           ┆           ┆ 93280633  ┆           │
│ 98178   ┆ 311145.402 ┆ 279000    ┆ 1700000   ┆ … ┆ 3         ┆ 7         ┆ 6.8049792 ┆ 241       │
│         ┆ 48962655   ┆           ┆           ┆   ┆           ┆           ┆ 53112033  ┆           │
│ 98055   ┆ 303375.786 ┆ 293500    ┆ 631000    ┆ … ┆ 3         ┆ 7         ┆ 7.125     ┆ 248       │
│         ┆ 2903226    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 98031   ┆ 302658.941 ┆ 289950    ┆ 800000    ┆ … ┆ 3         ┆ 7         ┆ 7.3960784 ┆ 255       │
│         ┆ 1764706    ┆           ┆           ┆   ┆           ┆           ┆ 31372549  ┆           │
│ 98198   ┆ 302157.864 ┆ 268000    ┆ 1350000   ┆ … ┆ 3         ┆ 7         ┆ 7.1003861 ┆ 259       │
│         ┆ 86486485   ┆           ┆           ┆   ┆           ┆           ┆ 00386101  ┆           │
│ 98003   ┆ 296484.406 ┆ 268000    ┆ 950000    ┆ … ┆ 3         ┆ 7         ┆ 7.5664062 ┆ 256       │
│         ┆ 25         ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆           │
│ 98030   ┆ 293317.739 ┆ 280000    ┆ 565000    ┆ … ┆ 3         ┆ 7         ┆ 7.4017094 ┆ 234       │
│         ┆ 3162393    ┆           ┆           ┆   ┆           ┆           ┆ 01709402  ┆           │
│ 98023   ┆ 287971.427 ┆ 269000    ┆ 1275000   ┆ … ┆ 3         ┆ 8         ┆ 7.5978494 ┆ 465       │
│         ┆ 95698927   ┆           ┆           ┆   ┆           ┆           ┆ 62365591  ┆           │
│ 98188   ┆ 286048.055 ┆ 264000    ┆ 707000    ┆ … ┆ 3         ┆ 7         ┆ 6.9920634 ┆ 126       │
│         ┆ 55555556   ┆           ┆           ┆   ┆           ┆           ┆ 92063492  ┆           │
│ 98148   ┆ 285211.020 ┆ 270000    ┆ 600600    ┆ … ┆ 3         ┆ 7         ┆ 6.8775510 ┆ 49        │
│         ┆ 40816325   ┆           ┆           ┆   ┆           ┆           ┆ 20408164  ┆           │
│ 98001   ┆ 282335.556 ┆ 260000    ┆ 850000    ┆ … ┆ 3         ┆ 7         ┆ 7.3095238 ┆ 336       │
│         ┆ 54761905   ┆           ┆           ┆   ┆           ┆           ┆ 09523809  ┆           │
│ 98032   ┆ 253325.25  ┆ 250000    ┆ 545000    ┆ … ┆ 4         ┆ 7         ┆ 7.175     ┆ 120       │
│ 98168   ┆ 241003.912 ┆ 235000    ┆ 600000    ┆ … ┆ 3         ┆ 6         ┆ 6.5019920 ┆ 251       │
│         ┆ 35059762   ┆           ┆           ┆   ┆           ┆           ┆ 3187251   ┆           │
│ 98002   ┆ 235085.470 ┆ 235000    ┆ 389000    ┆ … ┆ 4         ┆ 7         ┆ 6.7165775 ┆ 187       │
│         ┆ 5882353    ┆           ┆           ┆   ┆           ┆           ┆ 40106952  ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘